name: CapRover Deoploy

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: CapRover
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: AlexxNB/caprover-action@v1
        with:
          server: ${{secrets.CAPROVER_SERVER}}
          password: ${{secrets.CAPROVER_PASSWORD}}
          appname: ${{secrets.CAPROVER_APPNAMEDEV}}
          branch: main
