name: CapRover Deoploy

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deploy
        uses: YEK-PLUS/caprover-action@v1.1
        with:
          server: ${{secrets.CAPROVER_SERVER}}
          password: ${{secrets.CAPROVER_PASSWORD}}
          appname: ${{secrets.CAPROVER_APPNAMEDEV}}
          branch: main
          directory: ./backend
